### ISSUE TITLE
idea: flip css used in javascript/jquery.

### ISSUE THREAD

**Issue by shimondoodkin** [cssjanus/cssjanus#38]
like matching and changing
object.style.paddingRight=5;
object.css('padding-right',5);
object.css({'padding-right':5});
object.animate({'padding-right':5});
object.velocity({'padding-right':5});

**Comment by yonatan** [comment]
For jQuery you can override css and animate functions and flip at runtime. I've done something like that in https://github.com/yonatan/rtl-toolkit/blob/master/rtlx/rtlx.js and it works reasonably well as long as every css manipulation goes through jQuery. But a foolproof general-purpose solution is trickier because you have to account for packed and minimized js, stuff like ```s=obj.style; s.paddingRight=42;```, scripts loaded from CDNs, script tags added to DOM at runtime, eval() etc...

**Comment by Krinkle** [comment]
Changing CSS in JavaScript should be rare. Prefer setting classnames instead, which in turn trigger the necessary adjustments or transitions.

In some cases an explicit or dynamic adjustment is needed. For that I recommend inline constructs using something like `domElement.dir === 'rtl'` (local) or `document.documentElement.dir === 'rtl'` (global).
