### ISSUE TITLE
It's not possible to flip flexbox designs

### ISSUE THREAD

**Issue by CthulhuDev** [cssjanus/cssjanus#51]
Shouldn't a class that goes like this: 
`.class { display: flex; flex-direction: row; justify-content: flex-start; }`
be translated into:
`.class { display: flex; flex-direction: row-reverse; justify-content: flex-start; }`

As of the web demo, this doesn't happen.

**Comment by catrope** [comment]
Flipping `row` to `row-reverse` is not needed IMO, because if there is an ancestor with `dir="rtl"`, then `flex-direction: row; justify-content: flex-start;` already lays things out from right to left. The meanings of `start` and `end`, and of `row` and `row-reverse`, are already correctly inverted by the browser when in an RTL context.

**Comment by catrope** [comment]
For a demonstration of this, see: https://jsfiddle.net/pf8r8c7o/
