### ISSUE TITLE
Add a flag to swap direction in selectors

### ISSUE THREAD

**Issue by dralshehri** [cssjanus/cssjanus#9]
When you work on projects that's primarily RTL and you depend on stylesheets from different vendors who code for LTR use mainly, you'll face a small confusing issue in selectors that have hardcoded direction in them like rtl, left, right etc. because when you convert the stylesheets to RTL those selectors will have an opposite effect of they appear to do. This issue might not be important for projects that is mainly LTR but in the other way it counts.

Let's take for example one of the common bootstrap classes that show this problem:

```
.pull-right {
    float: right
}
```

will be converted to

```
.pull-right {
    float: left
}
```

As you can see, it's a bit confusing when used in html markup with RTL as the primary direction.

What I'm proposing here is to allow changing directions in selectors as an option or two like swapLtrRtlInSelector and swapLeftRightInSelector that are disabled by default.

**Comment by Krinkle** [comment]
From the initial description it sounds like you're under the impression that `pull-left` would be flipped, but not `pull-right`. However, selectors are preserved  in CSSJanus regardless of which directionality they are about.

As such, `@noflip` seems appropiate.

Changing directionality within the selectors seems undesirable as this would require a matching change in HTML content - which we want to avoid, by design.

If you do wish these kinds of rules to be flipped, the content to be affected, and the class names to make sense, I'd recommend renaming the classes to something more semantic by using directionality-neutral terms like "start" or "end".

This also matches how other CSS properties work internally. Such as the native default for `text-align` (which is `start`, not `left`), with a matching value of `end` for the opposite direction. See also the `flex-start` and `flex-end` values for the `justify-content` property from the CSS Flexbox features. These features work in different directions (left-to-right and right-to-left, but also top-to-bottom).
